"""init init

Revision ID: 28f916ac8575
Revises: None
Create Date: 2015-05-29 09:19:18.107811

"""

# revision identifiers, used by Alembic.
revision = '28f916ac8575'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
