"""initial migration

Revision ID: 33054ff78b23
Revises: 4e24f2b1b342
Create Date: 2015-10-02 13:44:46.087187

"""

# revision identifiers, used by Alembic.
revision = '33054ff78b23'
down_revision = '4e24f2b1b342'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
