"""initial migration

Revision ID: 4e24f2b1b342
Revises: None
Create Date: 2015-06-09 22:25:52.913397

"""

# revision identifiers, used by Alembic.
revision = '4e24f2b1b342'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
